module.exports = Object.freeze({
	DEFAULT_SOUND_VOLUME: 0.5,
	DEFAULT_SOUND_MIN_INTERVAL: 0,
	DEFAULT_SOUND_MAX_INTERVAL: 5,

	DEFAULT_ECHO_DELAY: 0.1,
	DEFAULT_ECHO_GAIN: 0.25,
	DEFAULT_ECHO_FILTER_FREQUENCY: 1100,
})